# Generated by Django 5.1.6 on 2025-05-20 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Consulta médica general', 'Consulta médica general'), ('Consulta de especialidad (Cardiología)', 'Consulta de especialidad (Cardiología)'), ('Consulta de especialidad (Dermatología)', 'Consulta de especialidad (Dermatología)'), ('Consulta de especialidad (Neurología)', 'Consulta de especialidad (Neurología)'), ('Análisis de sangre completo', 'Análisis de sangre completo'), ('Electrocardiograma (ECG)', 'Electrocardiograma (ECG)'), ('Resonancia Magnética (RMN)', 'Resonancia Magnética (RMN)'), ('Radiografía de tórax', 'Radiografía de tórax'), ('Colonoscopia', 'Colonoscopia')], max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrativo'), ('finanzas', 'Finanzas')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
