# Generated by Django 5.2 on 2025-06-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='autorizado_mutua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='numero_autorizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='datos_mutua',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mutua_verificada',
            field=models.BooleanField(default=False),
        ),
    ]
