# Generated by Django 5.2.3 on 2025-06-18 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0002_cita_autorizado_mutua_cita_numero_autorizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(related_name='invoices', to='betterhealth.service'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener 8 números seguidos de una letra (ejemplo: 12345678A).', regex='^\\d{8}[A-Za-z]$')]),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener 8 números seguidos de una letra (ejemplo: 12345678A).', regex='^\\d{8}[A-Za-z]$')]),
        ),
    ]
