# Generated by Django 5.2 on 2025-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0002_cita_estado_cita_importe_alter_cita_servicio_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='numero_poliza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='tiene_mutua',
            field=models.BooleanField(default=False),
        ),
    ]
