# Generated by Django 5.1.6 on 2025-05-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterhealth', '0003_alter_cita_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('service_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('included_in_mutual', models.BooleanField()),
                ('duration_minutes', models.IntegerField()),
                ('requires_mutual_authorization', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betterhealth.service'),
        ),
    ]
