# Generated by Django 5.1.6 on 2025-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Consulta médica general', 'Consulta médica general'), ('Consulta de especialidad (Cardiología)', 'Consulta de especialidad (Cardiología)'), ('Consulta de especialidad (Dermatología)', 'Consulta de especialidad (Dermatología)'), ('Consulta de especialidad (Neurología)', 'Consulta de especialidad (Neurología)'), ('Análisis de sangre completo', 'Análisis de sangre completo'), ('Electrocardiograma (ECG)', 'Electrocardiograma (ECG)'), ('Resonancia Magnética (RMN)', 'Resonancia Magnética (RMN)'), ('Radiografía de tórax', 'Radiografía de tórax'), ('Colonoscopia', 'Colonoscopia')], max_length=255),
        ),
    ]
