name: Histogram Issues Report Generator

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub
  schedule:
    - cron: '0 0 * * 1'  # Ejecuta cada lunes a las 00:00 UTC

jobs:
  generate-histogram:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub matplotlib

      - name: Run histogram generator script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          python .github/scripts/histogram.py
      
      - name: Verify generated files
        run: |
          ls -la histogram_issues.png && echo "Histogram image generated correctly" || echo "Histogram image not found"
      
      - name: Upload Histogram as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: histogram-files
          path: |
            histogram_issues.png
